version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: webmo2024
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d  # Dein backup.sql wird geladen und ausgef체hrt
      - ./data:/var/lib/postgresql/data  # Persistiert Daten, um sie nach Neustarts zu behalten
    ports:
      - "5432:5432"  # Datenbank ist auf diesem Port erreichbar

  backend:
    build:
      context: ./server  # Verzeichnis des Backends
      dockerfile: Dockerfile  # Dockerfile im /server-Verzeichnis
    volumes:
      - ./server:/usr/src/app  # Das Verzeichnis des Backend-Codes wird eingebunden
      - /usr/src/app/node_modules  # Verhindert Konflikte mit node_modules
    ports:
      - "3001:3001"  # Backend l채uft auf Port 3001
    depends_on:
      - db  # Das Backend wartet auf die Datenbank
    environment:
      DATABASE_URL: postgres://sa:123@db:5432/webmo2024  # Verbindung zur PostgreSQL-Datenbank

  frontend:
    build:
      context: .  # Verzeichnis des Frontends ist das Root-Verzeichnis
      dockerfile: Dockerfile  # Dockerfile im Root-Verzeichnis
    ports:
      - "5173:80"  # Vue.js-Frontend l채uft 체ber Nginx auf Port 80, wird auf 5173 gemappt
    depends_on:
      - backend  # Frontend wartet, bis das Backend bereit ist
